---
- name: reload systemd daemon
  command: "systemctl daemon-reload"
  listen: reload systemd

- name: restart iptables
  service: name=iptables state=restarted
  listen: restart iptables

- name: reboot
  command: whoami

- name: enable iptables
  command: systemctl enable iptables

