---
# tasks file for l2tp
- name: Install apt packages
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
      - pptpd
  notify: enable pptpd

- name: generate pptpd.conf
  template:
    src: pptpd.conf
    dest: /etc/pptpd.conf
  notify: restart pptpd

- name: copy pptpd-options
  copy:
    src: pptpd-options
    dest: /etc/ppp/pptpd-options
  notify: restart pptpd

- name: generate chap-secrets
  template:
    src: chap-secrets.vault
    dest: /etc/ppp/chap-secrets
  notify: restart pptpd

- name: generate ip-up rules
  template: 
    src: ip-up-routes.sh
    dest: /etc/ppp/ip-up.d/routes
    mode: '500'
